function getAverage(scores) {
    // Defines a function named 'getAverage' that calculates the average score from an array of scores.

    let sum = 0;
    // Initializes a variable 'sum' to store the cumulative total of all scores in the array.
    // This variable will be updated as each score is processed in the loop.

    for (const score of scores) {
        // Begins a loop that iterates over each individual score in the 'scores' array.

        sum += score;
        // Adds the current score (represented by 'score') to the 'sum' variable.
        // This line updates the total sum with the value of the current score during each iteration.
    }

    return sum / scores.length;
    // Divides the total 'sum' of all scores by the number of elements in the 'scores' array.
    // Returns the calculated average to the caller of the function.
}

function getGrade(score) {
    // Defines a function named 'getGrade' that determines the grade corresponding to a given score.

    if (score === 100) {
        // Checks if the given score is exactly 100.

        return "A++";
        // If the score is 100, returns the grade "A++", indicating a perfect score.
    } else if (score >= 90) {
        // Checks if the score is greater than or equal to 90 but less than 100.

        return "A";
        // If the condition is true, returns the grade "A".
    } else if (score >= 80) {
        // Checks if the score is greater than or equal to 80 but less than 90.

        return "B";
        // If the condition is true, returns the grade "B".
    } else if (score >= 70) {
        // Checks if the score is greater than or equal to 70 but less than 80.

        return "C";
        // If the condition is true, returns the grade "C".
    } else if (score >= 60) {
        // Checks if the score is greater than or equal to 60 but less than 70.

        return "D";
        // If the condition is true, returns the grade "D".
    } else {
        // Executes this block if none of the previous conditions are met, meaning the score is below 60.

        return "F";
        // Returns the grade "F" for scores below 60.
    }
}

function hasPassingGrade(score) {
    // Defines a function named 'hasPassingGrade' to check if a given score corresponds to a passing grade.

    return getGrade(score) !== "F";
    // Calls the 'getGrade' function with the given score and checks if the returned grade is not "F".
    // If the grade is not "F", the function returns true (indicating a passing grade).
    // If the grade is "F", the function returns false (indicating a failing grade).
}

function studentMsg(totalScores, studentScore) {
    // Defines a function named 'studentMsg' that generates a personalized message about the student's performance.
    // Takes two arguments: 'totalScores', an array of all student scores, and 'studentScore', the score of the specific student.

    let classAverage = getAverage(totalScores);
    // Calls the 'getAverage' function with the 'totalScores' array to calculate the average score of the class.
    // Stores the resulting average score in the variable 'classAverage'.

    let studentGrade = getGrade(studentScore);
    // Calls the 'getGrade' function with the student's score to determine their grade.
    // Stores the resulting grade in the variable 'studentGrade'.

    let passGrade = hasPassingGrade(studentScore);
    // Calls the 'hasPassingGrade' function with the student's score to check if they passed.
    // Stores the result (true or false) in the variable 'passGrade'.

    if (passGrade === true) {
        // Checks if 'passGrade' is true, meaning the student passed the course.

        return "Class average: " + classAverage + ". Your grade: " + studentGrade + ". You passed the course.";
        // If the student passed, constructs and returns a message containing:
        // 1. The class average score.
        // 2. The student's grade.
        // 3. A statement indicating that the student passed the course.
    } else {
        // Executes this block if 'passGrade' is false, meaning the student failed the course.

        return "Class average: " + classAverage + ". Your grade: " + studentGrade + ". You failed the course.";
        // Constructs and returns a message containing:
        // 1. The class average score.
        // 2. The student's grade.
        // 3. A statement indicating that the student failed the course.
    }
}

console.log(studentMsg([92, 88, 12, 77, 57, 100, 67, 38, 97, 89], 37));
// Calls the 'studentMsg' function with the class scores array and the specific student's score (37).
// Logs the personalized message generated by the 'studentMsg' function to the console.
